apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: 428156589112.dkr.ecr.eu-west-1.amazonaws.com/workshop-frontend:175045ddea670de23342b8526d40165b1e071332
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://<BACKEND_ALB_DNS>/api/tasks"  # Replace with your backend ALB DNS after deploy: kubectl get ing -n workshop
        ports:
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 2
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #      path: /
        #      port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   successThreshold: 1
